ci: fix Docker container build
nerves-project/nerves_system_br pull request #666
Opened 2022-07-23 03:43 UTC by fhunleth

2022-07-23 14:20 UTC, jjcarstens reviewed
Seems like this isn't quite fixed?

2022-07-23 16:19 UTC, fhunleth commented
No, I pinged Digit for help.

2022-07-25 22:27 UTC, doawoo commented on .circleci/config.yml
> +      docker buildx build --platform linux/arm64,linux/amd64 $DOCKER_PATH
```suggestion
       apk add --no-cache docker-cli-buildx
       docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
       docker buildx create --name multiarch --driver docker-container --use
       docker buildx build --platform linux/arm64,linux/amd64 $DOCKER_PATH
```

There's apparently a bug in Docker... https://github.com/docker/buildx/issues/495

2022-07-25 22:38 UTC, doawoo requested changes

2022-07-25 22:38 UTC, doawoo commented on .circleci/config.yml
> +       docker buildx build --platform linux/arm64,linux/amd64 $DOCKER_PATH
```suggestion
       apk add --no-cache docker-cli-buildx
       docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
       docker context create multiarch
       docker buildx create multiarch --driver docker-container --use
       docker buildx build --platform linux/arm64,linux/amd64 $DOCKER_PATH
```

MAYBE this one?? CI debugging is painful :(

2022-07-27 00:55 UTC, doawoo commented
OK! I think I have finally figured out the dark arts of creating a multi-arch docker image. Turns out you cannot just push one easily outside of using `--push` in the `buildx` sub-command. So I build them individually, push them as dev tags, then combine them into a single `manifest` which will act like a "unified" AMD64/ARM64 image when pulled.

NOTE: we cannot test the ARM image easily in CircleCI, they do not support Docker ARM execution very well, and, it would simply take forever...

2022-07-27 12:31 UTC, fhunleth commented
@doawoo You're a hero! Thank you for figuring this out!!!!!

2022-07-27 12:33 UTC, merged