Support 'find' for MacOS Sonoma
nerves-project/nerves_system_br pull request #771
Opened 2024-01-18 22:13 UTC by CaptChrisD

`find` in recent macOS Sonoma -- or possibly due to a Xcode command line tool update -- changed and now matches Linux's.

Instead of leave conditional check from Darwin I am proposing using a simple `||`.

Note: during `mix firmware` if the first `find` fails output to STDERR so a line similar to `find: .../_build/_nerves-tmp/rootfs_overlay/srv/erlang/lib/nautic_net_device-0.1.2/priv/arm/tailscale: unknown primary or operator` will occur.

2024-01-19 23:51 UTC, jjcarstens requested changes
I think this will need some more work. With my setup, the first `find` passes, but doesn't properly exclude. My system needs the `eval` for whatever reason to properly exclude.

It might be we make this more manual and iterate through executables to remove the ones with a matching `no scrub` directory

2024-01-27 17:41 UTC, fhunleth commented
@jjcarstens @CaptChrisD What are your thoughts on this one? I'm ready to make a 1.26.0 release. If you both are too busy, I'm ok with pushing it to a 1.26.1 release.

2024-01-27 18:07 UTC, jjcarstens commented
I'm adjusting this right now. It should be a simple fix

2024-01-28 00:44 UTC, fhunleth commented
Fixed in #777. Thanks @CaptChrisD for getting this started.

2024-01-28 00:44 UTC, closed without merging